### ISSUE TITLE
Submitting Archived Build Error

### ISSUE THREAD

**Issue by RDKeith** [petroakzhygitov/nest-ios-sdk#1]
Still seeing the "Found an unexpected Mach-O header code: 0x72613c21" error when submitting a build.  

Based on our previous discussions, I recall this was a static-library issue.  Just checking to see if anything new has been created.  Thanks!

-Keith

**Comment by petroakzhygitov** [comment]
Hi, Keith!

I've updated develop branch with possible fix. 
Please, add this line to you `Podfile`, make `pod install` and let me know if it helps
`pod 'NestSDK', :git => 'https://github.com/petroakzhygitov/nest-ios-sdk.git', :branch => 'develop'`

Petro
