### ISSUE TITLE
NestSDKDemoAdvanced won't run

### ISSUE THREAD

**Issue by slum44** [petroakzhygitov/nest-ios-sdk#2]
Hi,

I'm trying to run your NestSDKDemoAdvanced sample, and I'm getting the following when trying to run up.

Any idea how to resolve?

Thanks

2016-09-04 10:36:35.247 NestSDKDemoAdvanced[19079:1899031] **\* Assertion failure in -[UITableView _configureCellForDisplay:forIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UITableView.m:7971
2016-09-04 10:36:35.253 NestSDKDemoAdvanced[19079:1899031] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView (<UITableView: 0x7fa35204e200; frame = (0 64; 414 672); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x7fa350753c50>; layer = <CALayer: 0x7fa35074e3c0>; contentOffset: {0, -64}; contentSize: {414, 138}>) failed to obtain a cell from its dataSource (<DevicesViewController: 0x7fa3507308f0>)'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010fde7d85 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010f859deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010fde7bea +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x000000010f4a2d5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   UIKit                               0x0000000110bfb4b1 -[UITableView _configureCellForDisplay:forIndexPath:] + 225
    5   UIKit                               0x0000000110c0751e -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 808
    6   UIKit                               0x0000000110c0762c -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
    7   UIKit                               0x0000000110bdbd4f -[UITableView _updateVisibleCellsNow:isRecursive:] + 2996
    8   UIKit                               0x0000000110c10686 -[UITableView _performWithCachedTraitCollection:] + 92
    9   UIKit                               0x0000000110bf7344 -[UITableView layoutSubviews] + 224
    10  UIKit                               0x0000000110b64980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    11  QuartzCore                          0x000000011095fc00 -[CALayer layoutSublayers] + 146
    12  QuartzCore                          0x000000011095408e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    13  QuartzCore                          0x0000000110953f0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    14  QuartzCore                          0x00000001109483c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    15  QuartzCore                          0x0000000110976086 _ZN2CA11Transaction6commitEv + 486
    16  QuartzCore                          0x00000001109767f8 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
    17  CoreFoundation                      0x000000010fd0cc37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    18  CoreFoundation                      0x000000010fd0cba7 __CFRunLoopDoObservers + 391
    19  CoreFoundation                      0x000000010fd027fb __CFRunLoopRun + 1147
    20  CoreFoundation                      0x000000010fd020f8 CFRunLoopRunSpecific + 488
    21  GraphicsServices                    0x00000001143dead2 GSEventRunModal + 161
    22  UIKit                               0x0000000110aa9f09 UIApplicationMain + 171
    23  NestSDKDemoAdvanced                 0x000000010e775caf main + 111
    24  libdyld.dylib                       0x000000011218592d start + 1
    25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by petroakzhygitov** [comment]
@slum44 Thanks for mentioning the problem! I've fixed it. Please, check it in NestSDK 0.1.5

**Comment by slum44** [comment]
Thanks that fix worked
